back-end/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inventory.urls',namespace='inventory')),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'


urlpatterns = [
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"), 
    path('logout/', views.logoutUser, name="logout"), 
    
    path('manage/', views.ManageListView.as_view(),name='manage'),
    
    path('add_user/', views.CreateUser.as_view(),name='user'),
    path('', views.LocationListView.as_view(),name='index'),
    path('location/create/',views.LocationCreateView.as_view(),name='create'),
    path('products/',views.ProductListView.as_view(),name='products'),
    path('product/<slug:slug>/update/',views.ProductUpdateView.as_view(),name='product_update'),
    path('location/<slug:slug>/',views.LocationDetailView.as_view(),name='location'),
    path('move/<slug:slug>/<slug:location_slug>/',views.add_movement,name='movement'),
    path('move_out/<slug:slug>/<slug:location_slug>/',views.move_out,name='move_out'),
    path('delete/<int:id>/',views.delete_location,name='delete'),
    path('destroy/<int:id>',views.delete_view),
    path('useractive/<int:ky>', views.ActivateUser),
    path('userdeactive/<int:ky>', views.DeactivateUser)
]

templates/add_user.html
<!-- User Modal -->
<div class="modal fade" id="addUser" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add User </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'inventory:user' %}" method="post">
          {% csrf_token %}
          {{form}}
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary btn-sm">Add User</button>
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

templates/all_products.html
{% extends 'base.html' %}

{% block title %}All Products{% endblock title %}

{% block content %}

<h3>All Products
  <p class="float-right">Total Count : {{total_qty}}</p>
</h3>
<table class="table table-striped table-sm">
    <thead class='text-center thead-dark'>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Location</th>
        <th scope="col">Quantity</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody class='text-center'>
    {% for product in products %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{product.name}}</td>
        <td>{{product.location}}</td>
        <td>{{product.qty}}</td>
        <td>
          <a href="{% url 'inventory:product_update' product.slug %}" class="btn btn-sm btn-outline-success">Update</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

templates/delete_location.html
{% extends 'index.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}

<form action="" method="post" class="text-center">
    {% csrf_token %}
    <p>Are you sure to delete {{location.name}}?</p>
    <div>
        <button type="submit" class="btn btn-danger btn-sm">Confirm</button>
        <a href="{{location.get_absolute_url}}" class="btn btn-secondary btn-sm">Go back</a>
    </div>
    
</form>


{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<h3 class="mb-3"><a href="{% url 'inventory:products' %}" class="btn btn-sm btn-info">All Products</a>
<button class="btn btn-sm btn-outline-info float-right" data-toggle="modal" data-target="#addLocation">Add Location</button>
{% include 'add_location.html' %}
</h3>
<table class="table table-striped table-sm">
    <thead class='text-center thead-dark'>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Location</th>
        <th scope="col">Total Quantity</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody class='text-center'>
    {% for location in locations %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{location.name}}</td>
        <td>
          {% if location.total_quantity > 0 %}{{location.total_quantity}}{% else %}0{% endif %}
        </td>
        <td> <a class="btn btn-success btn-sm" href="{{location.get_absolute_url}}">Manage</a> 
            <a class="btn btn-danger btn-sm" href="delete/{{location.id}}" >Delete</a> </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 50;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
            text-align:center
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
				    <p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'inventory:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

templates/manage.html
{% extends 'base.html' %}

{% block title %}Users{% endblock title %}

{% block content %}

<h3>Manage Users
    <button class="btn btn-info float-right btn-sm" data-toggle="modal" data-target="#addUser">Add User</button>
    {% include 'add_user.html' %}
    </h3>
    <table class="table table-striped table-sm">
        <thead class='text-center thead-dark'>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody class='text-center'>
        {% for user in users %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{user.username}}</td>
            <td>{{user.email}}</td>
            <td>
              <a class="btn btn-success btn-sm" href="/useractive/{{user.id}}">Approve</a>
              <a href="" class="btn btn-danger btn-sm">Reject</a>
              <a href="/userdeactive/{{user.id}}" class="btn btn-danger btn-sm">Suspend</a>
              <a href="/destroy/{{user.id}}" class="btn btn-danger btn-sm" >Delete</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock content %}

templates/navbar.html
<style>
  .hello-msg{
    font-size: 18px;
    color: rgb(20, 18, 18);
    margin-right: 20px;
  }
</style>


<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">
    Home
  </a>
  {% if request.user.is_staff %}
  <a class="navbar-brand" href="{% url 'inventory:manage' %}">Manage</a>
  {% endif %}
  <span  class="hello-msg">Welcome, {{request.user}} <a class="navbar-brand" href="{% url 'inventory:logout' %}">Logout</a></span>
 
</nav>

templates/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 50;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
			text-align:center
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'inventory:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>